# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Peter Rowe's Website
email: peterrowe.tech@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My blog, portfolio, and playground for anything tech.
twitter_username: playerpeter1231
github_username: playerpeter1231
minimal_mistakes_skin: air
search: false

teaser: /assets/images/BlogPictures/Devlog2.4.jpg
og_image: /assets/images/BlogPictures/Devlog2.4.jpg

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Helsinki

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Peter Rowe"
  avatar : "/assets/images/BlogPictures/SquareProfPic.jpg"
  bio    : "Tech enthusiast and motivated programmer"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/@playerpeter1231"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/playerpeter1231"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:peterrowe.tech@gmail.com"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/@playerpeter1231"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/playerpeter1231"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:peterrowe.tech@gmail.com"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _previous work
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
portfolio:
  type: liquid
  path: /portfolio/

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/